### ISSUE TITLE
Wrong/unclear answer on question with ID 19

### ISSUE THREAD

**Issue by masinamichele** [gHashTag/javascriptcamp_bot#1]
Hello,
I was trying out the quiz and found a question which answer was not clear.

I'm talking specifically about the question with ID 19, which is this one:

https://github.com/gHashTag/javascriptcamp_bot/blob/3c31275202ccfd480ae22384b43a13d82c3654f9/quiz/en.js#L136-L142

The question is unclear, as all three answers appear to be right. I thought about that a bit, and in the end I answered `const`, because, technically, both `let` and `var` are used to define _variables_, but `const` is used for, well, _constants_.

After that, I was greeted with an error and saw the correct answer was `var`. It was then that I realized the question could be asking "what keyword are we not using _anymore_ to define variables", to which I would have replied `var`, even if all the previous questions used `var` in them.

What I suggest is either rewording the question to make it clearer, or throw in a blatantly wrong answer like `object` instead of `var`. Maybe I got it wrong because I'm not a native english speaker and I have missed the clarity of the question, but I believe a little edit can prevent future errors.

Thank you for your time. Have a nice day!

**Comment by gHashTag** [comment]
Good issue. 
Changed the question to "What keyword are we not using anymore to define variables"?
